name: Build

permissions:
  contents: write

on:
  create:
  workflow_dispatch:
    inputs:
      uploadAssets:
        description: 'Upload Assets'
        type: boolean
        required: false
        default: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, self-hosted-arm64]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        # node-gyp doesn't work on python 3.12 due to missing distutils on mac and windows.
        python-version: '3.10'
      if: ${{ matrix.os == 'windows-latest' || matrix.os == 'macos-latest' }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - run: npm install

    - run: npm run prebuildify-${{ matrix.os }}

    - run: npm run prebuildify-upload -- ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event.inputs.uploadAssets == 'true' }}
