name: Build

permissions:
  contents: write

on:
  create:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      uploadAssets:
        description: 'Upload Assets'
        type: boolean
        required: false
        default: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14, self-hosted-arm64]
        runtime_versions: [
          [electron, 28.0.0],
          [electron, 29.0.0],
          [node, 18.0.0],
          [node, 19.0.0],
          [node, 20.0.0],
          [node, 21.0.0],
        ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        # node-gyp doesn't work on python 3.12 due to missing distutils on mac and windows.
        python-version: '3.10'
      # this action does not have 3.10 available for linux arm64 (or any version at time of checking).
      # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
      if: ${{ matrix.os != 'self-hosted-arm64' }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - run: npm install

    - run: npm run prebuildify-host -- -r ${{ matrix.runtime_versions[0] }} -t ${{ matrix.runtime_versions[1] }}

    - run: npm run prebuildify-upload -- ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event.inputs.uploadAssets == 'true' }}
